---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/yaml-lint.yml
platforms:
  - name: centos6
    image: tonyskidmore/docker-centos6-ansible
    tmpfs:
      - /run
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos7
    image: tonyskidmore/docker-centos7-ansible
    tmpfs:
      - /run
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos8
    image: tonyskidmore/docker-centos8-ansible
    tmpfs:
      - /run
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu1804
    image: tonyskidmore/docker-ubuntu1804-ansible
    tmpfs:
      - /run
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian9
    image: tonyskidmore/docker-debian9-ansible
    tmpfs:
      - /run
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      gathering: smart
      gather_subset: min
  inventory:
    group_vars:
      all:
        ansible_user: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - destroy
verifier:
  name: ansible
  env:
    ANSIBLE_GATHERING: smart
    ANSIBLE_GATHER_SUBSET: min
  lint:
    name: ansible-lint
